### PR TITLE
Add translated document: glsl-extension.zh.md

### PR DESCRIPTION
**Pull request by whyb**
Add translated document: glsl-extension.zh.md

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4818) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4818) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nihui<br/>:x: whyb<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4818) it.</sub>

**Comment by whyb** [comment]
@nihui 这个translate版就先维持基于原滋原味的 `glsl-extension.md` 嘛🙈，至于qgroup所说的后面要补充的前置知识分享再分到其他pr上这样好不？

**Comment by nihui** [comment]
> @nihui 这个translate版就先维持基于原滋原味的 `glsl-extension.md` 嘛🙈，至于qgroup所说的后面要补充的前置知识分享再分到其他pr上这样好不？

请把文中的 NCNN 改成 ncnn

**Comment by whyb** [comment]
> > @nihui 这个translate版就先维持基于原滋原味的 `glsl-extension.md` 嘛🙈，至于qgroup所说的后面要补充的前置知识分享再分到其他pr上这样好不？
> 
> 请把文中的 NCNN 改成 ncnn

Edited

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
