### PR TITLE
fix fscanf -Wunused-result

### PR DESCRIPTION
**Pull request by ncnnnnn**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2205) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2205) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: nihui<br/>:x: sf<br/>:x: ncnnnnn<br/><hr/>**sf** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2205) it.</sub>

**Review by nihui — CHANGES_REQUESTED** [review]
```const Option& opt```
改为
```const Option& /* opt */```

这是 ncnn 对于参数的写法

**Comment by proydakov** [comment]
Hi, ncnnnnn .

I see `Merge remote-tracking branch 'ncnn-orig/master'` in you PR.
Could you fetch tencent/ncnn second origin and do git rebase tencent/ncnn ?

  231  git remote add tencent git@github.com:Tencent/ncnn.git
  233  git fetch tencent
  235  git rebase tencent/master
  509  git push -f

**Comment by ncnnnnn** [comment]
> `const Option& opt`
> 改为
> `const Option& /* opt */`
> 
> 这是 ncnn 对于参数的写法

因为看到下面有用到 (opt); ，用demo测试，编辑器会提示未定义错误。所以才用网上这种改法。

**Comment by ncnnnnn** [comment]
> Hi, ncnnnnn .
> 
> I see `Merge remote-tracking branch 'ncnn-orig/master'` in you PR.
> Could you fetch tencent/ncnn second origin and do git rebase tencent/ncnn ?
> 
> 231 git remote add tencent [git@github.com](mailto:git@github.com):Tencent/ncnn.git
> 233 git fetch tencent
> 235 git rebase tencent/master
> 509 git push -f

thank you!

**Pull request merged**
