### PR TITLE
fix vulkan memory leak issue

### PR DESCRIPTION
**Pull request by chenxiemin**
fix vulkan memory leak issue

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3088) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3088) before we can accept your contribution.<br/><hr/>**xiemchen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=3088) it.</sub>

**Comment by nihui** [comment]
Thanks for your contribution !

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
**[PR Description](https://github.com/Tencent/ncnn/pull/3088)** updated to latest commit (https://github.com/Tencent/ncnn/commit/423b62a703ef4f6e80969340f72e696d50eec5e8)

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
**[PR Description](https://github.com/Tencent/ncnn/pull/3088)** updated to latest commit (https://github.com/Tencent/ncnn/commit/423b62a703ef4f6e80969340f72e696d50eec5e8)

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
**[PR Description](https://github.com/Tencent/ncnn/pull/3088)** updated to latest commit (https://github.com/Tencent/ncnn/commit/423b62a703ef4f6e80969340f72e696d50eec5e8)

**Comment by chenxiemin** [comment]
Preparing review...

**Comment by chenxiemin** [comment]
## PR Reviewer Guide 🔍

Here are some key observations to aid the review process:

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 3 🔵🔵🔵⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<a href='https://github.com/Tencent/ncnn/pull/3088/files#diff-72d71abf643e7beba92861b56eaf81a8f4ee6cdd2188e4dd3b20b0397ea0a1d4R2343-R2344'><strong>Memory Leak</strong></a><br>The `delete` statement in line 2343 may not be sufficient to prevent memory leaks. It's recommended to use a smart pointer or a container to manage the memory.

</td></tr>
</table>

**Comment by chenxiemin** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by chenxiemin** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by chenxiemin** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by chenxiemin** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by chenxiemin** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by chenxiemin** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by chenxiemin** [comment]
Preparing PR description...

**Comment by chenxiemin** [comment]
**[PR Description](https://github.com/Tencent/ncnn/pull/3088)** updated to latest commit (https://github.com/Tencent/ncnn/commit/423b62a703ef4f6e80969340f72e696d50eec5e8)

**Comment by chenxiemin** [comment]
Preparing review...

**Comment by chenxiemin** [comment]
## PR Reviewer Guide 🔍

Here are some key observations to aid the review process:

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

<a href='https://github.com/Tencent/ncnn/pull/3088/files#diff-72d71abf643e7beba92861b56eaf81a8f4ee6cdd2188e4dd3b20b0397ea0a1d4R2343-R2343'><strong>Memory Leak Fix</strong></a><br>Ensure that the `delete` statement is properly handling the memory allocation and deallocation.

</td></tr>
</table>

**Comment by chenxiemin** [comment]
Preparing changelog updates...

**Comment by chenxiemin** [comment]
**Changelog updates:** 🔄

Here is the updated CHANGELOG.md file:

## 2024-10-14

### Fixed
Fixed a memory leak issue in Vulkan-based command processing, enhancing reliability and robustness.


>to commit the new content to the CHANGELOG.md file, please type:
>'/update_changelog --pr_update_changelog.push_changelog_changes=true'

**Comment by chenxiemin** [comment]
Preparing answer...

**Comment by chenxiemin** [comment]
### **Ask**❓
"give me a score of review effort"

### **Answer:**
As the PR-Reviewer, I'll provide a score of review effort based on the changes introduced in this pull request.

**Review Effort Score: 6/10**

Here's my reasoning:

* The change is relatively small and focused on fixing a specific memory leak issue.
* The code modification is straightforward, with only one addition (+) to the existing `VkCompute::submit_and_wait()` function.
* The commit message is clear and concise, providing context about the bug fix.

However, I would have liked to see:

* A bit more explanation in the commit message about why this specific memory leak was causing issues or how it affects the overall reliability of the Vulkan-based command processing.
* Perhaps a brief description of any testing or validation done to ensure the fix is effective and doesn't introduce new bugs.

Overall, the review effort required for this PR is moderate, as I need to verify that the change addresses the intended issue and doesn't have any unintended consequences.

**Pull request merged**
