### PR TITLE
小改一波文档试试水

### PR DESCRIPTION
**Pull request by LJoson**
1.github的markdown语法[toc]生成目录是不起作用的，用了点小手段试试效果
2.更改了一下文件命名

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4107) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4107) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4107) it.</sub>

**Comment by tpoisonooo** [comment]
要改为啥不把别的也改了。

**Comment by ysh329** [comment]
> 要改为啥不把别的也改了。

可能是想先看看效果

**Comment by LJoson** [comment]
对，大家觉得可以就一起改改看

**Pull request closed without merging**
