### PR TITLE
fix errors while build in Android Open Source Code"arm_usability.h:20…

### PR DESCRIPTION
**Pull request by caofx0418**
…:17 use of undeclared identifier 'round'"

error info:
In file included from vendor/hxxxsilicon/subsystem/ai/third-party/ncnn-20230223/src/layer/arm/cast_arm_bf16.cpp:20:
In file included from vendor/hxxxsilicon/subsystem/ai/third-party/ncnn-20230223/src/layer/arm/cast_bf16.h:14:
vendor/hxxxsilicon/subsystem/ai/third-party/ncnn-20230223/src/layer/arm/arm_usability.h:20:17: error: use of undeclared identifier 'round'
    int int32 = round(v);
                ^
vendor/hxxxsilicon/subsystem/ai/third-party/ncnn-20230223/src/layer/arm/arm_usability.h:128:17: error: use of undeclared identifier 'round'
    int int32 = round(v);

2 errors generated.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4622) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4622) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4622) it.</sub>

**Comment by caofx0418** [comment]
after modify include header, the AOSP(Android Open Source Code) build success, ncnn can use in Android system service and vendor hal service


============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=12
TARGET_PRODUCT=xxxx
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a55
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=cortex-a55
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-Ubuntu-18.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=SP2A.220305.012
OUT_DIR=out
============================================
[W][2023-04-13T18:52:06-0700][3433] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2023-04-13T18:52:06-0700][3433] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2023-04-13T18:52:06-0700][3499] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2023-04-13T18:52:06-0700][3499] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2023-04-13T18:52:07-0700][3624] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2023-04-13T18:52:07-0700][3624] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2023-04-13T18:52:07-0700][4425] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2023-04-13T18:52:07-0700][4425] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2023-04-13T18:52:07-0700][4443] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2023-04-13T18:52:07-0700][4443] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[100% 16/16] Copy: out/target/product/xxxx/obj/SHARED_LIBRARIES/libncnn_intermediates/libncnn.so.toc

**Comment by caofx0418** [comment]
在Google Pixel 6中，通过benchncnn，对比NDK编译和AOSP中编译2种方式的性能，无性能下降，如下如下：
NDK 25编译，性能结果：
          squeezenet  min =    6.51  max =    7.64  avg =    7.01
     squeezenet_int8  min =    5.96  max =    6.06  avg =    5.99
           mobilenet  min =   10.86  max =   10.94  avg =   10.90
      mobilenet_int8  min =    6.85  max =    6.94  avg =    6.90
        mobilenet_v2  min =    7.35  max =    7.44  avg =    7.39
        mobilenet_v3  min =    6.27  max =    6.93  avg =    6.55
          shufflenet  min =    4.16  max =    4.20  avg =    4.18
       shufflenet_v2  min =    4.04  max =    4.09  avg =    4.06
             mnasnet  min =    7.12  max =    7.53  avg =    7.28
     proxylessnasnet  min =    8.52  max =    8.54  avg =    8.53
     efficientnet_b0  min =   13.20  max =   13.36  avg =   13.27
   efficientnetv2_b0  min =   22.18  max =   22.22  avg =   22.21
        regnety_400m  min =    9.60  max =    9.65  avg =    9.63
           blazeface  min =    2.06  max =    2.09  avg =    2.08
           googlenet  min =   30.76  max =   30.85  avg =   30.82
      googlenet_int8  min =   25.31  max =   25.44  avg =   25.37
            resnet18  min =   16.78  max =   16.89  avg =   16.83
       resnet18_int8  min =   24.79  max =   24.94  avg =   24.88
             alexnet  min =   29.20  max =   29.26  avg =   29.23
               vgg16  min =   90.41  max =   90.66  avg =   90.55
          vgg16_int8  min =  197.79  max =  198.22  avg =  197.99
            resnet50  min =   49.39  max =   49.54  avg =   49.48
       resnet50_int8  min =   48.94  max =   49.14  avg =   49.04
      squeezenet_ssd  min =   20.88  max =   21.42  avg =   21.03
 squeezenet_ssd_int8  min =   23.78  max =   24.52  avg =   24.04
       mobilenet_ssd  min =   23.88  max =   23.91  avg =   23.90
  mobilenet_ssd_int8  min =   15.78  max =   15.84  avg =   15.82


AOSP System，性能结果：
          squeezenet  min =    6.57  max =    7.78  avg =    7.14
     squeezenet_int8  min =    5.75  max =    5.84  avg =    5.80
           mobilenet  min =   10.84  max =   10.90  avg =   10.87
      mobilenet_int8  min =    6.75  max =    6.81  avg =    6.78
        mobilenet_v2  min =    7.27  max =    7.35  avg =    7.30
        mobilenet_v3  min =    6.14  max =    6.24  avg =    6.17
          shufflenet  min =    4.17  max =    4.21  avg =    4.19
       shufflenet_v2  min =    3.79  max =    3.82  avg =    3.81
             mnasnet  min =    7.00  max =    7.05  avg =    7.03
     proxylessnasnet  min =    8.36  max =    8.47  avg =    8.40
     efficientnet_b0  min =   13.09  max =   13.17  avg =   13.13
   efficientnetv2_b0  min =   20.73  max =   20.85  avg =   20.78
        regnety_400m  min =    9.19  max =    9.31  avg =    9.26
           blazeface  min =    2.13  max =    2.17  avg =    2.15
           googlenet  min =   29.11  max =   29.21  avg =   29.17
      googlenet_int8  min =   23.86  max =   23.96  avg =   23.92
            resnet18  min =   16.67  max =   16.80  avg =   16.74
       resnet18_int8  min =   24.19  max =   24.27  avg =   24.23
             alexnet  min =   27.74  max =   27.98  avg =   27.88
               vgg16  min =   91.36  max =   91.57  avg =   91.48
          vgg16_int8  min =  197.63  max =  198.03  avg =  197.79
            resnet50  min =   49.22  max =   49.31  avg =   49.27
       resnet50_int8  min =   48.07  max =   48.13  avg =   48.10
      squeezenet_ssd  min =   20.08  max =   20.70  avg =   20.28
 squeezenet_ssd_int8  min =   22.84  max =   23.47  avg =   23.05
       mobilenet_ssd  min =   23.45  max =   23.55  avg =   23.50
  mobilenet_ssd_int8  min =   15.19  max =   15.32  avg =   15.28
      mobilenet_yolo  min =   48.64  max =   48.77  avg =   48.70
  mobilenetv2_yolov3  min =   26.72  max =   26.84  avg =   26.79
         yolov4-tiny  min =   35.34  max =   35.47  avg =   35.40
           nanodet_m  min =   10.11  max =   10.24  avg =   10.20
    yolo-fastest-1.1  min =    3.74  max =    3.76  avg =    3.75
      yolo-fastestv2  min =    3.69  max =    3.78  avg =    3.73
  vision_transformer  min =  887.31  max =  895.76  avg =  890.76
          FastestDet  min =    3.66  max =    3.73  avg =    3.69

**Review by nihui — APPROVED** [review]

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
