### PR TITLE
Fix 64 cpu

### PR DESCRIPTION
**Pull request by tpoisonooo**
fix  more than 64-cpu
关联 pr  https://github.com/Tencent/ncnn/pull/1973

### CODE REVIEW

**Comment by tpoisonooo** [comment]
https://restyled.io/gh/Tencent/repos/ncnn/jobs/367069 
重新提了一个，看了错误发现得大佬出手  @nihui

**Comment by nihui** [comment]
你试试重新 fork 下 Tencent/ncnn

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2078) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2078) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tpoisonooo<br/>:x: restyled-commits<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2078) it.</sub>

**Comment by tpoisonooo** [comment]
> 你试试重新 fork 下 Tencent/ncnn

大约是因为我喜欢 rebase -i 合并 commit message 导致的...瞎猜。

**Comment by nihui** [comment]
请修复 ci 编译错误

**Comment by tpoisonooo** [comment]
算了再开一个，再也不 force 了。

**Pull request closed without merging**
