### PR TITLE
fix(examples): exit program if load_param, load_model failed for clear message

### PR DESCRIPTION
**Pull request by zchrissirhcz**

### CODE REVIEW

**Comment by zchrissirhcz** [comment]
For https://github.com/Tencent/ncnn/issues/3982

**Review by nihui — CHANGES_REQUESTED** [review]
load function returns 0 if success
thus, the condition shall check any non-zero value for any potential failure

**Comment by zchrissirhcz** [comment]
Checking zero/nonzero now.
My rebase failed to push to origin, thus made an new commit.

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
