### PR TITLE
remove x86 reshape layers

### PR DESCRIPTION
**Pull request by Timen**
I ran into a regression using the reshape avx layers. I won't have time to look into it in the near future so I thought it would be best to remove them for now till I or someone else has a proper look at it and adds tests to cover the regression. It seemed something to do with tensorflow style reshape on a packed blob.

### CODE REVIEW

**Comment by nihui** [comment]
For the tensorflow style reshape, do you mean reshape with param 3=1 ？

**Comment by Timen** [comment]
Correct, and I also see that this value is not actually tested outside the default value in the ctest. I'm not able to contribute in the foreseeable future but would be good is someone could add a test case covering the permute value being set to 1 instead of zero.

**Comment by nihui** [comment]
reshape with permute implemented and tests included

**Comment by Timen** [comment]
@nihui thanks for picking this up so fast!

**Pull request closed without merging**
