### PR TITLE
Using new version of glslang. Fixed several compile warnings: [-Wsign-compare], [-Wunused-parameter]

### PR DESCRIPTION
**Pull request by proydakov**
Hi, NCNN Team.

As I see we have several compile warnings in glslang dependency. I commented several patcher to original glslang repository.
Is it possible to migrate on new glslang version?

https://github.com/Tencent/ncnn/runs/1732549148?check_suite_focus=true

[ 42%] Building CXX object glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/Versions.cpp.o
/home/runner/work/ncnn/ncnn/glslang/glslang/MachineIndependent/Versions.cpp: In member function ‘virtual void glslang::TParseVersions::initializeExtensionBehavior()’:
/home/runner/work/ncnn/ncnn/glslang/glslang/MachineIndependent/Versions.cpp:170:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int ii = 0; ii < sizeof(exts) / sizeof(exts[0]); ii++) {
                      ~~~^~~~~~~~~~~~~~~~~~~~~~~~

/home/runner/work/ncnn/ncnn/glslang/glslang/MachineIndependent/reflection.cpp: In member function ‘void glslang::TReflection::buildCounterIndices(const glslang::TIntermediate&)’:
/home/runner/work/ncnn/ncnn/glslang/glslang/MachineIndependent/reflection.cpp:1134:60: warning: unused parameter ‘intermediate’ [-Wunused-parameter]
 void TReflection::buildCounterIndices(const TIntermediate& intermediate)
                                                            ^~~~~~~~~~~~
                                                            
Best regards, Proydakov Evgeny.

### CODE REVIEW

**Comment by nihui** [comment]
Hi
I have considered upgrading to a higher version of glslang, but glslang currently introduces python as a build requirement. Therefore, users must install python to enable vulkan to build ncnn. Although python is easily accessible on almost all platforms, it does bring some burden.

I suggest waiting for glslang upsteam to remove the python build requirement before upgrading

https://github.com/KhronosGroup/glslang/issues/2496

**Comment by proydakov** [comment]
Sounds good.

**Comment by proydakov** [comment]
I removed python3 dependency from glslang master main source tree. Could you review it, pls ?

https://github.com/KhronosGroup/glslang/pull/2526

https://github.com/KhronosGroup/glslang/issues/2496

**Comment by nihui** [comment]
awesome work !

**Pull request merged**
