### PR TITLE
chore(examples): add YOLOX to ncnn examples

### PR DESCRIPTION
**Pull request by FateScript**
Please kindly review @nihui

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3110) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=3110) it.</sub>

**Comment by nihui** [comment]
please fix build error with c++11 disabled
enable github action on your fork to let code format work properly

**Comment by FateScript** [comment]
Seems this pr passes CI.  Plz review if any contributor is available. FYI @nihui

**Comment by nihui** [comment]
Hi, please fix ci error. Thanks !

**Comment by FateScript** [comment]
> Hi, please fix ci error. Thanks !

Update now.

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
