### PR TITLE
fix warning:delete called on non-final 'PoolAllocator/UnlockedPoolAll…

### PR DESCRIPTION
**Pull request by rogerou**
…ocator' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=589) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=589) before we can accept your contribution.<br/><hr/>**Roger** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=589) it.</sub>

**Comment by rogerou** [comment]
纯虚的接口类也需要virtual 析构函数

**Comment by rogerou** [comment]
@nihui 注册了呀 ，怎么显示没有？recheck就是404...

**Comment by nihui** [comment]
重新新建个 pr 试试看...

**Pull request closed without merging**
