### PR TITLE
test_clip.cpp: Add unittest of clip

### PR DESCRIPTION
**Pull request by xieydd**
As the title.

### CODE REVIEW

**Comment by nihui** [comment]
RandomMat fills the mat with values ranging -2 ~ 2, use 6 as the clip max may not proper here

**Comment by xieydd** [comment]
@nihui , i see, change 6 to 2 is ok? or change the RandomMat is better?

**Comment by nihui** [comment]
Mat a = RandomMat(100, 100, 16)
Randomize(a, -10.f, 10.f);

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
