### PR TITLE
Extract on CPU without pack/fp16fp32

### PR DESCRIPTION
**Pull request by MarsTechHAN**

### CODE REVIEW

**Review by nihui — CHANGES_REQUESTED** [review]
```int _unchange```
change the parameter identifier to a more meaningful one

**Comment by MarsTechHAN** [comment]
> `int _unchange`
> change the parameter identifier to a more meaningful one

@nihui How about `int extract_without_modify`?

**Review by MarsTechHAN — COMMENTED** [review]
Change to type and add comments in net.h

**Comment by nihui** [comment]
> Change to type and add comments in net.h

also apply your changes to net.cpp

**Review by nihui — APPROVED** [review]

**Pull request merged**
