### PR TITLE
Add POWER8 VSX toolchains

### PR DESCRIPTION
**Pull request by JeremyRand**
POWER8, though slower than POWER9, is still used in the wild; these toolchains should still be much faster on POWER8 than POWER8 without VSX optimizations.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4853) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4853) before we can accept your contribution.<br/><hr/>**Jeremy Rand** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4853) it.</sub>

**Comment by nihui** [comment]
Adding cpu model parameters to qemu can test these specific optimizations more directly

qemu-ppc64le -cpu power8_v2.0
qemu-ppc64le -cpu power9_v2.0

**Comment by JeremyRand** [comment]
> Adding cpu model parameters to qemu can test these specific optimizations more directly

Is this what you had in mind? (I wasn't quite sure about the syntax, hopefully I guessed right.)

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
