### PR TITLE
ARM: layernorm neon/fp16s/fp16sa/bf16s

### PR DESCRIPTION
**Pull request by EdVince**
完成了layernorm的arm部分：
1. neon:pack1,pack4
2. fp16s:pack1,pack4,pack8
3. fp16sa:pack1,pack4,pack8
4. bf16s:pack1,pack4

(PS:犀牛鸟计划的工作)

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4102) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4102) it.</sub>

**Comment by tpoisonooo** [comment]
没加 tests 和 benchmark.

**Comment by EdVince** [comment]
需要额外加吗？现在的test应该都够了吧。

**Comment by EdVince** [comment]
中文注释都去掉了，up有空看看代码吗😊 @nihui

**Pull request closed without merging**
