### PR TITLE
support torch.t to ncnn

### PR DESCRIPTION
**Pull request by XiaBing992**

### CODE REVIEW

**Comment by nihui** [comment]
torch.t 转换到 permute，不用新实现个layer

**Comment by XiaBing992** [comment]
> torch.t 转换到 permute，不用新实现个layer

**Comment by XiaBing992** [comment]
好的 我看看

**Comment by nihui** [comment]
用 GraphRewriterPass 实现这个转换，可以参考
https://github.com/Tencent/ncnn/blob/master/tools/pnnx/src/pass_ncnn/torch_mm.cpp
https://github.com/Tencent/ncnn/blob/master/tools/pnnx/src/pass_ncnn/torch_clamp.cpp

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4933) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4933) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4933) it.</sub>

**Pull request closed without merging**
