### PR TITLE
Add yolov8 ncnn example

### PR DESCRIPTION
**Pull request by whyb**
# Add yolov8 ncnn example

ReadMe
Convert yolov8 model to ncnn model workflow:

## step 1:
If you don't want to train the model yourself. You should go to the ultralytics website download the pretrained model file.
original pretrained model from [https://docs.ultralytics.com/models/yolov8/#supported-tasks-and-modes](https://docs.ultralytics.com/models/yolov8/#supported-tasks-and-modes)

## step 2:
run this command.
```shell
conda create --name yolov8 python=3.11
conda activate yolov8
pip install ultralytics onnx numpy protobuf
```

## step 3:
save source code file(export_model_to_ncnn.py): 
```python
from ultralytics import YOLO
detection_models = [
    ["./Detection-pt/yolov8n.pt", "./Detection-pt/"],
    ["./Detection-pt/yolov8s.pt", "./Detection-pt/"],
    ["./Detection-pt/yolov8m.pt", "./Detection-pt/"],
    ["./Detection-pt/yolov8l.pt", "./Detection-pt/"],
    ["./Detection-pt/yolov8x.pt", "./Detection-pt/"]
]
for model_dict in detection_models:
    model = YOLO(model_dict[0])  # load an official pretrained weight model
    model.export(format="ncnn", dynamic=True, save_dir=model_dict[1], simplify=True)
```

## step 4:
run command: 
```shell
python export_model_to_ncnn.py
```

## Test Image:

input image(640x640):
640x640

output image(640x640):
output

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5506) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5506) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nihui<br/>:x: whyb<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=5506) it.</sub>

**Review by nihui — APPROVED** [review]

**Comment by nihui** [comment]
Thanks for your contribution !

**Comment by SIXGODLI** [comment]
Traceback (most recent call last):
  File "D:\yolo\yolov8\export_model_to_ncnn.py", line 1, in <module>
    from ultralytics import YOLO
  File "C:\ProgramData\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "C:\ProgramData\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\ProgramData\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\base.py", line 15, in <module>
    from torch.utils.data import Dataset
  File "C:\ProgramData\anaconda3\envs\yolov8\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\ProgramData\anaconda3\envs\yolov8\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
2024年8月21日 按照流程报错了

**Comment by SIXGODLI** [comment]
通过转换之后，param也只有一个输出，无法使用ncnn自带的yolov8进行推理

**Comment by whyb** [comment]
> 通过转换之后，param也只有一个输出，无法使用ncnn自带的yolov8进行推理

圖片

yolov8 是一个输入1个，输出1个，您遇到的转换问题是因为没安装好环境，或者您是通过的ultralytics源码安装的，且并未使用requirement.txt，或者是python版本过低。

能否提供一些更加具体的问题描述呢？

如果ultralytics官方转换ncnn的方式走不通，不妨试试这种：导出torchscript （pt），然后再使用pnnx进行转换到ncnn模型。

**Comment by whyb** [comment]
> 按照examples/yolov8.cpp 教程转换成ncnn后用C++推理报错 image

您截图上的报错是因为没有读取到对应的模型文件：`yolov8n.param` 和 `yolov8n.bin`  ，可能的原因很多，有可能因为权限，有可能因为路径包含亚洲字符，也可能模型文件不存在。

**Comment by carldiashacker2023** [comment]
dynamic=True is not supported for ncnn export

**Comment by whyb** [comment]
> dynamic=True is not supported for ncnn export

You could try new convert function.
* pytorch to torchscript. 
* torchscript to pnnx.
* modify pnnx.
* pnnx to ncnn.

https://github.com/Tencent/ncnn/blob/master/examples/yolov8.cpp#L4

**Pull request merged**
