### PR TITLE
Add LogSoftmax and LogSigmoid support

### PR DESCRIPTION
**Pull request by lrw04**
The patch adds LogSoftmax and LogSigmoid layers to ncnn and respective passes to pnnx.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4921) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=4921) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=4921) it.</sub>

**Comment by lrw04** [comment]
Wait, is it better to rewrite logsigmoid/logsoftmax nodes into a log node and a sigmoid/softmax node in pnnx's pass_ncnn? This helps removing duplicate code but achieving higher numerical stability is impossible with this solution.

**Comment by nihui** [comment]
> Wait, is it better to rewrite logsigmoid/logsoftmax nodes into a log node and a sigmoid/softmax node in pnnx's pass_ncnn? This helps removing duplicate code but achieving higher numerical stability is impossible with this solution.

For code reuse, additional parameters can be added to the existing sigmoid/softmax
In this way, there is no need to add additional layer types

**Comment by lrw04** [comment]
Is it better to rewrite logxxx nodes into a log node + a xxx node? I will submit another PR soon.

**Pull request closed without merging**
