### PR TITLE
add android surface render

### PR DESCRIPTION
**Pull request by yyangoO**
add android surface render
add swapchain for any vulkan surface
add convert image to `VK_FORMAT_R8G8B8A8_UNORM` format pipeline and compute command
add `VK_FORMAT_R8G8B8A8_UNORM` allocator for image resource

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3211) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3211) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=3211) it.</sub>

**Comment by yyangoO** [comment]
testing repository: [](https://github.com/yyangoO/cam-ncnn-win)
now it can render `VkImageMat` to surface with `VkRender`, `Convert2R8g8b8a8UnormPipeline`, and `VkR8g8b8a8UnormImageAllocator`
but it seems that there are something wrong with the android `AHardwareBuffer` importing

**Comment by yyangoO** [comment]
now android surface render function works well (fixed the bugs of [convert2r8g8b8a8.comp](https://github.com/yyangoO/ncnn/blob/master/src/convert2_r8g8b8a8.comp) shader)
testing repository is [cam-ncnn-win](https://github.com/yyangoO/cam-ncnn-win), but there are still some bugs of android hardwarebuffer importing of ncnn, when testing in MI8 with MIUI12.5.1, ncnn can't use `VK_ANDROID_external_memory_android_hardware_buffer` extension
so I forked the repository [ncnn-android-yolox](https://github.com/yyangoO/ncnn-android-yolox) and edit [a few lines](https://github.com/yyangoO/ncnn-android-yolox/blob/7d80e7c4811e4da8445018d2d6fc8a671e61a64d/app/src/main/jni/ndkcamera.cpp#L737) to test the android surface render, and it's good to reviewed

**Comment by yyangoO** [comment]
more tests:

1. origin camera picture render


2. resizing camera picture render
 



3. rotating camera picture render




4. type changing camera picture render

**Pull request closed without merging**
