### PR TITLE
Add some mips layers

### PR DESCRIPTION
**Pull request by nullptr-leo**
Add AbsVal, Bias and Clip layer.

### CODE REVIEW

**Comment by nihui** [comment]
please update your info in the copyright header
setup travis ci for mips building

**Comment by nullptr-leo** [comment]
> please update your info in the copyright header
> setup travis ci for mips building

done.

**Comment by nihui** [comment]
I am not sure if testing __MIPS_MSA macro is the proper way as I found some opensource projects testing these macros.

```
__mips_msa
__mips_isa_rev
__mips_isa_rev >= 5
```

**Comment by nullptr-leo** [comment]
> I am not sure if testing __MIPS_MSA macro is the proper way as I found some opensource projects testing these macros.
> 
> ```
> __mips_msa
> __mips_isa_rev
> __mips_isa_rev >= 5
> ```

`__mips_msa` is defined by compiler and universal. `__MIPS_MSA` is defined explicitly in the mips cmake toolchain file, using `add_definitions(-D__MIPS_MSA)` like `add_definitions(-D__ARM_NEON)` for naming style consistency. so how about using `__mips_msa` directly in future commits?

**Comment by nihui** [comment]
> 
> 
> > I am not sure if testing __MIPS_MSA macro is the proper way as I found some opensource projects testing these macros.
> > ```
> > __mips_msa
> > __mips_isa_rev
> > __mips_isa_rev >= 5
> > ```
> 
> `__mips_msa` is defined by compiler and universal. `__MIPS_MSA` is defined explicitly in the mips cmake toolchain file, using `add_definitions(-D__MIPS_MSA)` like `add_definitions(-D__ARM_NEON)` for naming style consistency. so how about using `__mips_msa` directly in future commits?

yeah ! use __mips_msa

**Pull request merged**
