### PR TITLE
add Yolox

### PR DESCRIPTION
**Pull request by ncnnnnn**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3102) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=3102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=3102) it.</sub>

**Comment by zchrissirhcz** [comment]
Seems a good example. But why closed.

**Comment by zchrissirhcz** [comment]
Visual Studio's test_padding failed, this seems to be an known bug of gitlab CI.

On local Visual Studio, can't reproduce that failure.

**Comment by ncnnnnn** [comment]
应该由 [YOLOX](https://github.com/Megvii-BaseDetection/YOLOX)  @FateScript   提交比较好。
只是奇怪没有return也能过，记录下。 CXX11估计也要改。 ：）

**Comment by FateScript** [comment]
> 应该由 [YOLOX](https://github.com/Megvii-BaseDetection/YOLOX) @FateScript 提交比较好。
> 只是奇怪没有return也能过，记录下。 CXX11估计也要改。 ：）

感谢，这个问题我们已经发现了，在Android App中fix了这个问题，但是cpp应该是忘了fix了，最近因为要赶另一个工程项目，YOLOX的pr大概会在下周

**Comment by ncnnnnn** [comment]
辛苦，谢谢！

**Pull request closed without merging**
