### PR TITLE
Fix warnings on Visual Studio

### PR DESCRIPTION
**Pull request by chosungmann**

### CODE REVIEW

**Comment by nihui** [comment]
hi, please fix the build error reported by travis ci

**Comment by chosungmann** [comment]
I've fixed the build errors on Android!
Please take a look thanks!

**Comment by chosungmann** [comment]
But I'm having trouble signing the CLA. When I try to click "I agree" button on the CLA page, the red "sign error" message is coming out. I sent an email on this to tencentopen@tencent.com but haven't received a reply yet. Could you check this issue? Thanks in advance!

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
