### PR TITLE
fix requant relu6 bug

### PR DESCRIPTION
**Pull request by xieydd**
As the title, just change the backend x86.

### CODE REVIEW

**Comment by nihui** [comment]
```
ncnn::ParamDict pd;
pd.set(0, activation_params[0] * top_blob_int8_scale);// min
pd.set(1, activation_params[1] * top_blob_int8_scale);// max
activation->load_param(pd);
```

Move these loading stuff of activation to create_pipeline()

All pipelines should never be changed inside forward/forward_inplace, that would cause data race in multithreading application.

**Comment by xieydd** [comment]
> ```
> ncnn::ParamDict pd;
> pd.set(0, activation_params[0] * top_blob_int8_scale);// min
> pd.set(1, activation_params[1] * top_blob_int8_scale);// max
> activation->load_param(pd);
> ```
> 
> Move these loading stuff of activation to create_pipeline()
> 
> All pipelines should never be changed inside forward/forward_inplace, otherwise it would cause data race in multithreading application.

`use_intt8_requant ` is set in confuse_networl after every layer create_pipeline? i am a little confuse it.about

**Comment by nihui** [comment]
> 
> 
> > ```
> > ncnn::ParamDict pd;
> > pd.set(0, activation_params[0] * top_blob_int8_scale);// min
> > pd.set(1, activation_params[1] * top_blob_int8_scale);// max
> > activation->load_param(pd);
> > ```
> > 
> > 
> > Move these loading stuff of activation to create_pipeline()
> > All pipelines should never be changed inside forward/forward_inplace, otherwise it would cause data race in multithreading application.
> 
> `use_intt8_requant ` is set in `confuse_network` after every layer create_pipeline? i am a little confuse about it.
> 
> Can i change the order of `load_model create_pipeline fuse_nettwork ` to `load_model fuse_nettwork create_pipeline`?

The confuse_network function is actually a legacy issue, and may probably removed in the future.
But for now, I think it is fine to adjust this order or make changes to it, as long as it could work.

**Comment by xieydd** [comment]
@nihui Temporary solution.

**Comment by nihui** [comment]
OK, but that's it

**Pull request merged**
