### PR TITLE
type conversion and MSVC _CRT_SECURE_NO_DEPRECATE warning fix

### PR DESCRIPTION
**Pull request by kalcohol**
edit file list: caffe2ncnn.cpp ncnnoptimize.cpp
1. type conversion warning fix, for printf() and operator=
2. _CRT_SECURE_NO_DEPRECATE warning fix
3. tab to space, and add/remove some space

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=1524) <br/>All committers have signed the CLA.

**Comment by kalcohol** [comment]
peddling, behaver between gcc and msvc are different

**Comment by kalcohol** [comment]
Done.

**Comment by kalcohol** [comment]
next is NNIE

**Pull request merged**
