### PR TITLE
ncnn: test: Add support for ROIPooling test

### PR DESCRIPTION
**Pull request by monkeyking**

### CODE REVIEW

**Comment by nihui** [comment]
```
for (int i=0; i<11; i++)
```

What is this loop for ?

**Comment by monkeyking** [comment]
> ```
> for (int i=0; i<11; i++)
> ```
> 
> What is this loop for ?

U kn call it for more test or its useless

**Comment by nihui** [comment]
Thanks for your contribution !

**Comment by monkeyking** [comment]
失礼します
have not used ncnn before

**Comment by monkeyking** [comment]
> Thanks for your contribution !

失礼します
have not used ncnn before

**Pull request merged**
