### PR TITLE
docs: add docs about how to build a minimal ncnn library

### PR DESCRIPTION
**Pull request by songqun**
@nihui 如果有表述不清楚的地方，还请麻烦你指出了。。。

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2224) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2224) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2224) it.</sub>

**Comment by songqun** [comment]
@nihui 看上去由于网络原因(504 gateway)和神秘的apt install错误有两个pipeline挂了...有什么方法可以rehook并重跑pipeline吗？

**Comment by nihui** [comment]
> @nihui 看上去由于网络原因(504 gateway)和神秘的apt install错误有两个pipeline挂了...有什么方法可以rehook并重跑pipeline吗？

没关系，可以直接合并的，233

**Review by nihui — CHANGES_REQUESTED** [review]
```You can also drop layers and related optimized kernels by `-DWITH_LAYER_ABSVAL=OFF` as mentioned above.```
这里的 ABSVAL 得小写

**Comment by songqun** [comment]
> `` You can also drop layers and related optimized kernels by `-DWITH_LAYER_ABSVAL=OFF` as mentioned above. ``
> 这里的 ABSVAL 得小写

**Comment by songqun** [comment]
> `` You can also drop layers and related optimized kernels by `-DWITH_LAYER_ABSVAL=OFF` as mentioned above. ``
> 这里的 ABSVAL 得小写

感谢指出，已修改

**Review by nihui — APPROVED** [review]

**Comment by nihui** [comment]
合并啦，谢谢～～

**Pull request merged**
