### PR TITLE
add orangepi zero2 ncnn benchmark

### PR DESCRIPTION
**Pull request by wonderfullook**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5277) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5277) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=5277) it.</sub>

**Comment by nihui** [comment]
Thanks for your contribution !

**Comment by chainsx** [comment]
@wonderfullook 你人捏？

**Comment by wonderfullook** [comment]
> @wonderfullook 你人捏？

我啷个晓得

**Comment by dreamcmi** [comment]
> > @wonderfullook 你人捏？
> 
> 我啷个晓得

狗哥太强了

**Pull request merged**
