### PR TITLE
Add darknet to ncnn converter with YOLOv4 support.

### PR DESCRIPTION
**Pull request by zhiliu6**

### CODE REVIEW

**Comment by nihui** [comment]
please fix the ci error

**Comment by nihui** [comment]
add your copyright info in darknet2ncnn.cpp

**Comment by nihui** [comment]
NICE!

**Comment by nihui** [comment]
GREAT JOB!

**Comment by AlexeyAB** [comment]
So does NCNN now support YOLOv4? It isn't specified in the Readme.

**Pull request merged**
